#!/bin/bash

# This script is run by the deploy.altlab.dev webhook to update the deployed
# app.

set -eu
DIR="$(dirname -- "${0}")"

cd "${DIR}"

# Some day we might want to automatically pull the git repo that contains this
# deploy script, but for now changing the deploy process will require that
# to be done manually.
# git pull ...

make rebuild-frontend update-frontend-container
