version: '2.0'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: korp
      MYSQL_USER: korpikasutaja
      MYSQL_PASSWORD: korpiparool
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes: 
      - ./mysql:/docker-entrypoint-initdb.d      
  frontend:
    build: ./korp-frontend
    ports:
      - "9111:9111"
    restart: always
  backend:
    environment:
      - PYTHONUNBUFFERED=1 # otherwise docker-compose up won't show logs from this service
    build: ./korp-backend
    ports:
      - "1234:1234"
    restart: on-failure
