version: '2.0'
services:
  frontend:
    platform: linux/arm64	
    build: ./korp-frontend
    ports:
      - "9111:9111"
    restart: always
  backend:
    environment:
      - PYTHONUNBUFFERED=1 # otherwise docker-compose up won't show logs from this service
    platform: linux/arm64
    build: ./korp-backend
    ports:
      - "1234:1234"
    restart: on-failure
