dataset:
  A: A
  B: B
  C: C
  D: D
  G: G
  H: H
  I: I
  J: J
  K: K
  N: N
  O: O
  P: P
  Q: Q
  S: S
  U: U
  V: V
  X: X
  Y: Y
  Z: Z

escape: false
extendedcomponent: datasetSelect
label:
  eng: part-of-speech
  swe: ordklass
  est: sõnaliik
opts:
  is: '='
  isnot: '!='
order: 0
translation:
  A:
    eng: adjective
    swe: adjektiv
    est: omadussõna algvõrre
  B:
    eng: sentence particle
    swe: partikel
    est: lausepartikkel
  C:
    eng: adjective comparative
    swe: adjektiv
    est: omadussõna keskvõrre
  D:
    eng: adverb
    swe: adverb
    est: määrsõna
  G:
    eng: genitive attribute
    swe: genitive
    est: genitiivatribuut
  H:
    eng: proper noun
    swe: egennamn
    est: pärisnimi
  I:
    eng: interjection
    swe: interjektion
    est: hüüdsõna
  J:
    eng: conjunction
    swe: konjunktion
    est: sidesõna
  K:
    eng: adposition
    swe: adposition
    est: kaassõna
  N:
    eng: cardinal number
    swe: grundtal
    est: põhiarvsõna
  O:
    eng: ordinal number
    swe: ordningstal
    est: järgarvsõna
  P:
    eng: pronoun
    swe: pronomen
    est: asesõna
  Q:
    eng: foreign word
    swe: utländskt ord
    est: tundmatu
  S:
    eng: noun
    swe: substantiv
    est: nimisõna
  U:
    eng: adjective superlative
    swe: adjective
    est: omadussõna ülivõrre
  V:
    eng: verb
    swe: verb
    est: tegusõna
  X:
    eng: particle
    swe: partikel
    est: verbi juurde kuuluv sõna
  Y:
    eng: abbreviation
    swe: abbr
    est: lühend
  Z:
    eng: punctuation
    swe: interpunktion
    est: kirjavahemärk
