label:
  eng: dependency relation
  swe: dependensrelation
  est: sõltuvussuhted

extended_component: datasetSelect  
dataset:
    acl: acl
    acl:relcl: acl:relcl
    advcl: advcl
    advcl:relcl: advcl:relcl
    advmod: advmod
    advmod:emph: advmod:emph
    advmod:lmod: advmod:lmod
    amod: amod
    appos: appos
    aux: aux
    aux:pass: aux:pass
    case: case
    cc: cc
    cc:preconj: cc:preconj
    ccomp: ccomp
    clf: clf
    compound: compound
    compound:lvc: compound:lvc
    compound:prt: compound:prt
    compound:redup: compound:redup
    compound:svc: compound:svc
    conj: conj
    cop: cop
    csubj: csubj
    csubj:outer: csubj:outer
    csubj:pass: csubj:pass
    dep: dep
    det: det
    det:numgov: det:numgov
    det:nummod: det:nummod
    det:poss: det:poss
    discourse: discourse
    dislocated: dislocated
    expl: expl
    expl:impers: expl:impers
    expl:pass: expl:pass
    expl:pv: expl:pv
    fixed: fixed
    flat: flat
    flat:foreign: flat:foreign
    flat:name: flat:name
    goeswith: goeswith
    iobj: iobj
    list: list
    mark: mark
    nmod: nmod
    nmod:poss: nmod:poss
    nmod:tmod: nmod:tmod
    nsubj: nsubj
    nsubj:outer: nsubj:outer
    nsubj:pass: nsubj:pass
    nummod: nummod
    nummod:gov: nummod:gov
    obj: obj
    obl: obl
    obl:agent: obl:agent
    obl:arg: obl:arg
    obl:lmod: obl:lmod
    obl:tmod: obl:tmod
    orphan: orphan
    parataxis: parataxis
    punct: punct
    reparandum: reparandum
    root: root
    vocative: vocative
    xcomp: xcomp


    # acl: clausal modifier of noun (adnominal clause)
    # acl:relcl: relative clause modifier
    # advcl: adverbial clause modifier
    # advcl:relcl: adverbial relative clause modifier
    # advmod: adverbial modifier
    # advmod:emph: emphasizing word, intensifier
    # advmod:lmod: locative adverbial modifier
    # amod: adjectival modifier
    # appos: appositional modifier
    # aux: auxiliary
    # aux:pass: passive auxiliary
    # case: case marking
    # cc: coordinating conjunction
    # cc:preconj: preconjunct
    # ccomp: clausal complement
    # clf: classifier
    # compound: compound
    # compound:lvc: light verb construction
    # compound:prt: phrasal verb particle
    # compound:redup: reduplicated compounds
    # compound:svc: serial verb compounds
    # conj: conjunct
    # cop: copula
    # csubj: clausal subject
    # csubj:outer: outer clause clausal subject
    # csubj:pass: clausal passive subject
    # dep: unspecified dependency
    # det: determiner
    # det:numgov: pronominal quantifier governing the case of the noun
    # det:nummod: pronominal quantifier agreeing in case with the noun
    # det:poss: possessive determiner
    # discourse: discourse element
    # dislocated: dislocated elements
    # expl: expletive
    # expl:impers: impersonal expletive
    # expl:pass: reflexive pronoun used in reflexive passive
    # expl:pv: reflexive clitic with an inherently reflexive verb
    # fixed: fixed multiword expression
    # flat: flat expression
    # flat:foreign: foreign words
    # flat:name: names
    # goeswith: goes with
    # iobj: indirect object
    # list: list
    # mark: marker
    # nmod: nominal modifier
    # nmod:poss: possessive nominal modifier
    # nmod:tmod: temporal modifier
    # nsubj: nominal subject
    # nsubj:outer: outer clause nominal subject
    # nsubj:pass: passive nominal subject
    # nummod: numeric modifier
    # nummod:gov: numeric modifier governing the case of the noun
    # obj: object
    # obl: oblique nominal
    # obl:agent: agent modifier
    # obl:arg: oblique argument
    # obl:lmod: locative modifier
    # obl:tmod: temporal modifier
    # orphan: orphan
    # parataxis: parataxis
    # punct: punctuation
    # reparandum: overridden disfluency
    # root: root
    # vocative: vocative
    # xcomp: open clausal complement


