dataset:
  B-PER: B-PER
  B-LOC: B-LOC
  B-ORG: B-ORG
  

is_struct_attr: true
label:
  eng: name type
  swe: typ
  est: nimetüüp

translations:
  B-PER:
    est: isik
    eng: person

  B-LOC:
    est: koht
    eng: place

  B-ORG:
    est: asutus
    eng: organization
