context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
      est: 1 lõik
    value: 1 paragraph
description:
  swe: Koidula och Kreutzwald
  eng: Koidula and Kreutzwald correspondence
  est: Koidula ja Kreutzwaldi kirjavahetus
id: koidulakreutzwald
mode:
  - name: litterary


pos_attributes:
  - baseform: lemma
  - pos: epos
  - number: number
  - cases: case
  - voice: voice
  - tense: tense
  - nominal: nominal
  - mood: mood
  - person: person
  - negation: negation
  - name_type: nametype
  - footnote_id: notetype
  - div_orig: orig

struct_attributes:
  - text_author: sender
  - text_recipient: recipient
  - text_date: date

title:
  swe: 'Koidula-Kreutzwald'
  eng: 'Koidula-Kreutzwald'
  est: 'Koidula-Kreutzwald'
within:
  - label:
      eng: sentence
      swe: mening
      est: lause
    value: sentence
