context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
      est: 1 lõik
    value: 1 paragraph
  - label:
      eng: 1 sentence
      swe: 1 mening
    value: 1 sentence
description:
  swe: ParlaMint 2022
  eng: ParlaMint 2022 sample
  est: ParlaMint 2022 näidis
id: parlamint-ee_2022-06-17
mode:
  - name: parlamint


pos_attributes:
  - baseform: lemma
  - pos: udpos
  - msd: msd
  - name_type: ne_type
  - ref: ref
  - dephead: dephead
  - deprel: udeprel
    

struct_attributes:
  # - name_type: name_type
  - speech_id: id
  - speech_subcorpus: subcorpus
  - speech_term: term
  - speech_session: session
  - speech_meeting: meeting
  - speech_sitting: sitting
  - speech_agenda: agenda
  - speech_title: title
  - speech_speaker_role: speaker_role
  - speech_speaker_name: speaker_name
  - speech_speaker_mp: speaker_mp
  - speech_speaker_minister: speaker_minister
  - speech_speaker_party_name: ee_party_name
  - speech_party_status: party_status
  - speech_party_orientation: party_orientation
  - speech_speaker_gender: gender
  - speech_speaker_birth: speaker_year
  # - speech_date: date
    

title:
  swe: ParlaMint 2022
  eng: ParlaMint 2022
  est: ParlaMint 2022
within:
  - label:
      eng: sentence
      swe: mening
      est: lause
    value: sentence
