context:
  - label:
      eng: 1 sentence
      swe: 1 mening
      est: 1 lause
    value: 1 sentence
description:
  swe: Test korpus
  eng: Testing corpus
  est: Testkorpus
id: testcorpus
mode:
  - name: default


pos_attributes:
  - pos: pos

title:
  swe: 'Test korpus'
  eng: 'Test corpus'
  est: 'Testkorpus'
within:
  - label:
      eng: sentence
      swe: mening
      est: lause
    value: sentence
