context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
      est: 1 lõik
    value: 1 paragraph
description:
  swe: Under Ivask
  eng: Under and Ivask short
  est: Underi ja Ivaski kirjavahetus
id: underivask
mode:
  - name: litterary


pos_attributes:
  - baseform: lemma
  - pos: epos
  - number: number
  - cases: case
  - voice: voice
  - tense: tense
  - nominal: nominal
  - mood: mood
  - person: person
  - negation: negation

struct_attributes:
  - name_type: type
  - text_sender: sender
  - text_recipient: recipient
  - text_place: place
  - text_year: year
  - text_date: date
    

title:
  swe: 'Under-Ivask'
  eng: 'Under-Ivask'
  est: 'Under-Ivask'
within:
  - label:
      eng: sentence
      swe: mening
      est: lause
    value: sentence
