context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
      est: 1 lõik
    value: 1 paragraph
description:
  swe: Moderna
  eng: Modern
  est: Veebikorpus 2023 (<2014)
id: veeb2023_pre2014
mode:
  - name: default
    folder: veeb

pos_attributes:
  - baseform: lemma
  - pos: epos
  - msd: msd

    
struct_attributes:
  - paragraph_heading: heading
  - doc_feed_title: title
  - doc_timestamp_year: year
  - doc_date: date
  - doc_url: url
    

title:
  swe: 'Web 23'
  eng: 'Web 23'
  est: 'Veeb 2023 (<2014)'
  
within:
  - label:
      eng: sentence
      swe: mening
      est: lause
    value: sentence
