label:
  swe: Moderna
  eng: Modern
  est: EKI
order: 10
folders:
  veeb:
    title:
      eng: Web
      swe: Webb
      est: Veeb
    description:
      eng: Web texts
      swe: Webbtexter
      est: EKI veebikorpus 2023
